server:
  port: 8081

spring:
  application:
    name: Resource-Server
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://auth-server:9000


application:
  bucket:
    dash-analytics-test

cloud:
  aws:
    credentials:
      access-key: AKIA6GBMBK5VRFG6KFVK
      secret-key: bC8O2z9wrxCo1XlUz1/4bhdX5wcdVjSUKMGu9o2
    region:
      static: us-east-1
    stack:
      auto: false



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: localhost
